import type { Metadata } from 'next';
import { Comfortaa, Marmelad } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const comfortaa = Comfortaa({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-comfortaa',
});

const marmelad = Marmelad({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-marmelad',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
     
        <body
          className={clsx(
            comfortaa.variable,
            marmelad.variable,
            'transition-colors duration-500'
          )}
      >
        <Providers>
          {children}
        </Providers>
        </body>
     
    </html>
  );
}
